services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/app
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=/mlflow/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0

  prefect:
    image: prefecthq/prefect:2.14.12-python3.10
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=sqlite+aiosqlite:///prefect.db
    volumes:
      - ./flows:/flows
    command: >
      bash -c "
        prefect config set PREFECT_UI_ENABLED=true &&
        prefect server start
      "

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   depends_on:
  #     - prometheus

# volumes:
#   grafana-data:
